version: '3'
services:
  #database_produto:
  #  image: mongo:4.0
  #  container_name: 'mongo_db_produto'
  service_produto:
    image: nodeapp:0.1
    volumes: 
      - ./express-delivery-produto:/app/
    command: npm install && 
    ports: ["3000:80"]
    
    
